@startuml
' Definición de las clases y estructuras

class Bloque {
    +bool estado
    +RectangleShape bloque
}

class Pastilla {
    +bool estado
    +RectangleShape pastilla
}

class Vector2f {
    +float x
    +float y
    +Vector2f(float x, float y)
}

class CircleShape {
    +void setOrigin(float x, float y)
    +void setFillColor(Color color)
    +void setPosition(float x, float y)
    +Vector2f getPosition()
    +void move(float offsetX, float offsetY)
    +FloatRect getGlobalBounds()
}

class RectangleShape {
    +void setOrigin(float x, float y)
    +void setFillColor(Color color)
    +void setPosition(float x, float y)
    +Vector2f getPosition()
    +void move(float offsetX, float offsetY)
    +FloatRect getGlobalBounds()
    +void setSize(Vector2f size)
    +Vector2f getSize()
    +void setScale(float factorX, float factorY)
}

class RenderWindow {
    +void setFramerateLimit(unsigned int limit)
    +void draw(Drawable &drawable)
    +void clear()
    +void display()
    +bool isOpen()
    +bool pollEvent(Event &event)
    +Vector2u getSize()
}

class Font {
    +bool loadFromFile(string filename)
}

class Text {
    +void setFont(Font &font)
    +void setString(string text)
    +void setPosition(float x, float y)
}

class SoundBuffer {
    +bool loadFromFile(string filename)
}

class Sound {
    +void setBuffer(SoundBuffer &buffer)
    +void play()
}

class Event {
    +enum EventType { Closed }
    +EventType type
}

class Color {
    +static const Color Blue
    +static const Color Green
    +static const Color White
    +static const Color Cyan
    +static const Color Yellow
    +static const Color Magenta
}

class Keyboard {
    +static bool isKeyPressed(Key key)
    +enum Key { Right, Left }
}

' Relaciones entre las clases

Bloque --> RectangleShape
Pastilla --> RectangleShape
CircleShape --> Vector2f
RectangleShape --> Vector2f
RenderWindow --> Vector2u
Text --> Font
Sound --> SoundBuffer
Event --> EventType

arkanoid *-- Bloque
arkanoid *-- Pastilla
arkanoid *-- Vector2f
arkanoid *-- CircleShape
arkanoid *-- RectangleShape
arkanoid *-- RenderWindow
arkanoid *-- Font
arkanoid *-- Text
arkanoid *-- SoundBuffer
arkanoid *-- Sound
arkanoid *-- Event
arkanoid *-- Color
arkanoid *-- Keyboard
@enduml
